/* Auto-generated by genmsg_cpp for file /home/ai/rosbuild_ws/mlnpredicates/srv/MLNPredicates.srv */

package ros.pkg.mlnpredicates.srv;

import java.nio.ByteBuffer;


public class MLNPredicates extends ros.communication.Service<MLNPredicates.Request, MLNPredicates.Response> {

  public static java.lang.String __s_getDataType() { return "mlnpredicates/MLNPredicates"; }
  public static java.lang.String __s_getMD5Sum() { return "723d9aac36a8f458c6439a8f71c782b1"; }

  public java.lang.String getDataType() { return MLNPredicates.__s_getDataType(); }
  public java.lang.String getMD5Sum() { return MLNPredicates.__s_getMD5Sum(); }

  public MLNPredicates.Request createRequest() {
    return new MLNPredicates.Request();
  }

  public MLNPredicates.Response createResponse() {
    return new MLNPredicates.Response();
  }

static public class Request extends ros.communication.Message {

  public java.lang.String dummy = new java.lang.String();

  public Request() {
  }

  public static java.lang.String __s_getDataType() { return "mlnpredicates/MLNPredicatesRequest"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "5eab3f8fe195848369929fb790db61c1"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "723d9aac36a8f458c6439a8f71c782b1"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "string dummy\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Request clone() {
    Request c = new Request();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4 + dummy.length();
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, dummy);
  }

  public void deserialize(ByteBuffer bb) {
    dummy = Serialization.readString(bb);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Request))
      return false;
    Request other = (Request) o;
    return
      dummy.equals(other.dummy) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.dummy == null ? 0 : this.dummy.hashCode());
    return result;
  }
} // class Request

static public class Response extends ros.communication.Message {

  public java.util.ArrayList<ros.pkg.mlnpredicates.msg.MLNPredicate> predicates = new java.util.ArrayList<ros.pkg.mlnpredicates.msg.MLNPredicate>();

  public Response() {
  }

  public static java.lang.String __s_getDataType() { return "mlnpredicates/MLNPredicatesResponse"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "29e7df00c9ca72a3e0d0414a6ef671b8"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "723d9aac36a8f458c6439a8f71c782b1"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "MLNPredicate[] predicates\n" +
"\n" +
"\n" +
"================================================================================\n" +
"MSG: mlnpredicates/MLNPredicate\n" +
"string name\n" +
"string[] domain\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Response clone() {
    Response c = new Response();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4;
    for(ros.pkg.mlnpredicates.msg.MLNPredicate val : predicates) {
      __l += val.serializationLength();
    }
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.putInt(predicates.size());
    for(ros.pkg.mlnpredicates.msg.MLNPredicate val : predicates) {
      val.serialize(bb, seq);
    }
  }

  public void deserialize(ByteBuffer bb) {

    int __predicates_len = bb.getInt();
    predicates = new java.util.ArrayList<ros.pkg.mlnpredicates.msg.MLNPredicate>(__predicates_len);
    for(int __i=0; __i<__predicates_len; __i++) {
      ros.pkg.mlnpredicates.msg.MLNPredicate __tmp = new ros.pkg.mlnpredicates.msg.MLNPredicate();
      __tmp.deserialize(bb);
      predicates.add(__tmp);;
    }
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Response))
      return false;
    Response other = (Response) o;
    return
      predicates.equals(other.predicates) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.predicates == null ? 0 : this.predicates.hashCode());
    return result;
  }
} // class Response

} //class

