---
- query: 
    - hasSense
    - isGrounding
- closed_world:
    - hasSense
    - isPhrase
    - isaW
    - isaI
    - isInstanceOf
    - hasPOS
    - abbrev
    - acomp
    - advcl
    - advmod
    - agent
    - amod
    - appos
    - attr
    - aux
    - auxpass
    - cc
    - ccomp
    - complm
    - conj
    - cop
    - csubj
    - csubjpass
    - dep
    - det
    - dobj
    - xpl
    - infmod
    - iobj
    - mark
    - mwe
    - neg
    - nn
    - npadvmod
    - nsubj
    - nsubjpass
    - num
    - number
    - parataxis
    - partmod
    - pcomp
    - pobj
    - poss
    - possessive
    - preconj
    - predet
    - prep
    - prepc
    - prt
    - punct
    - purpcl
    - quantmod
    - rcmod
    - ref
    - rel
    - root
    - tmod
    - xcomp
    - xsubj
    - prep_to
    - prep_from
    - prep_of
    - prep_with
    - prep_for
    - prep_per
    - prep_on
    - prep_by
    - prep_in
    - prep_into
    - conj_and
    - conj_negcc
    - conj_or
    - prep_by_means_of
    - prep_in_accordance_with
    - prep_in_addition_to
    - prep_in_case_of
    - prep_in_front_of
    - prep_in_lieu_of
    - prep_in_place_of
    - prep_in_spite_of
    - prep_on_account_of
    - prep_on_behalf_of
    - prep_on_top_of
    - prep_with_regard_to
    - prep_with_respect_to
