/* Auto-generated by genmsg_java.py for file /home/ai/Documents/Aptana_Studio_3_Workspace/pracmln/rosmln/msg/AtomTruthValuePair.msg */

package ros.pkg.rosmln.msg;

import java.nio.ByteBuffer;

public class AtomTruthValuePair extends ros.communication.Message {

  public java.lang.String atom = new java.lang.String();
  public float prob;

  public AtomTruthValuePair() {
  }

  public static java.lang.String __s_getDataType() { return "rosmln/AtomTruthValuePair"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "adecce51bebbb6ad2257bbf8a2c81426"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "string atom\n" +
"float32 prob\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public AtomTruthValuePair clone() {
    AtomTruthValuePair c = new AtomTruthValuePair();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4 + atom.length();
    __l += 4; // prob
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, atom);
    bb.putFloat(prob);
  }

  public void deserialize(ByteBuffer bb) {
    atom = Serialization.readString(bb);
    prob = bb.getFloat();
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof AtomTruthValuePair))
      return false;
    AtomTruthValuePair other = (AtomTruthValuePair) o;
    return
      atom.equals(other.atom) &&
      prob == other.prob &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.atom == null ? 0 : this.atom.hashCode());
    result = prime * result + Float.floatToIntBits(this.prob);
    return result;
  }
} // class AtomTruthValuePair

