/* Auto-generated by genmsg_java.py for file /home/ai/Documents/Aptana_Studio_3_Workspace/pracmln/rosmln/msg/MLNConfig.msg */

package ros.pkg.rosmln.msg;

import java.nio.ByteBuffer;

public class MLNConfig extends ros.communication.Message {

  public java.lang.String mlnFiles = new java.lang.String();
  public java.lang.String db = new java.lang.String();
  public java.lang.String method = new java.lang.String();
  public java.lang.String engine = new java.lang.String();
  public java.lang.String output_filename = new java.lang.String();
  public boolean saveResults;
  public java.lang.String logic = new java.lang.String();
  public java.lang.String grammar = new java.lang.String();

  public MLNConfig() {
  }

  public static java.lang.String __s_getDataType() { return "rosmln/MLNConfig"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "20b394d21334fc7377ac1d71b7e4b8b9"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "string mlnFiles\n" +
"string db\n" +
"string method\n" +
"string engine\n" +
"string output_filename\n" +
"bool saveResults\n" +
"string logic\n" +
"string grammar\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public MLNConfig clone() {
    MLNConfig c = new MLNConfig();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4 + mlnFiles.length();
    __l += 4 + db.length();
    __l += 4 + method.length();
    __l += 4 + engine.length();
    __l += 4 + output_filename.length();
    __l += 1; // saveResults
    __l += 4 + logic.length();
    __l += 4 + grammar.length();
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, mlnFiles);
    Serialization.writeString(bb, db);
    Serialization.writeString(bb, method);
    Serialization.writeString(bb, engine);
    Serialization.writeString(bb, output_filename);
    bb.put((byte)(saveResults ? 1 : 0));
    Serialization.writeString(bb, logic);
    Serialization.writeString(bb, grammar);
  }

  public void deserialize(ByteBuffer bb) {
    mlnFiles = Serialization.readString(bb);
    db = Serialization.readString(bb);
    method = Serialization.readString(bb);
    engine = Serialization.readString(bb);
    output_filename = Serialization.readString(bb);
    saveResults = bb.get() != 0 ? true : false;
    logic = Serialization.readString(bb);
    grammar = Serialization.readString(bb);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof MLNConfig))
      return false;
    MLNConfig other = (MLNConfig) o;
    return
      mlnFiles.equals(other.mlnFiles) &&
      db.equals(other.db) &&
      method.equals(other.method) &&
      engine.equals(other.engine) &&
      output_filename.equals(other.output_filename) &&
      saveResults == other.saveResults &&
      logic.equals(other.logic) &&
      grammar.equals(other.grammar) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.mlnFiles == null ? 0 : this.mlnFiles.hashCode());
    result = prime * result + (this.db == null ? 0 : this.db.hashCode());
    result = prime * result + (this.method == null ? 0 : this.method.hashCode());
    result = prime * result + (this.engine == null ? 0 : this.engine.hashCode());
    result = prime * result + (this.output_filename == null ? 0 : this.output_filename.hashCode());
    result = prime * result + (this.saveResults ? 1231 : 1237);
    result = prime * result + (this.logic == null ? 0 : this.logic.hashCode());
    result = prime * result + (this.grammar == null ? 0 : this.grammar.hashCode());
    return result;
  }
} // class MLNConfig

