/* Auto-generated by genmsg_java.py for file /home/ai/Documents/Aptana_Studio_3_Workspace/pracmln/rosmln/msg/MLNDatabase.msg */

package ros.pkg.rosmln.msg;

import java.nio.ByteBuffer;

public class MLNDatabase extends ros.communication.Message {

  public java.util.ArrayList<ros.pkg.rosmln.msg.AtomProbPair> evidence = new java.util.ArrayList<ros.pkg.rosmln.msg.AtomProbPair>();

  public MLNDatabase() {
  }

  public static java.lang.String __s_getDataType() { return "rosmln/MLNDatabase"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "39d35ee1af4d2b76c41c0a4b3e192348"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "AtomProbPair[] evidence\n" +
"\n" +
"================================================================================\n" +
"MSG: rosmln/AtomProbPair\n" +
"string atom\n" +
"float32 prob\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public MLNDatabase clone() {
    MLNDatabase c = new MLNDatabase();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4;
    for(ros.pkg.rosmln.msg.AtomProbPair val : evidence) {
      __l += val.serializationLength();
    }
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.putInt(evidence.size());
    for(ros.pkg.rosmln.msg.AtomProbPair val : evidence) {
      val.serialize(bb, seq);
    }
  }

  public void deserialize(ByteBuffer bb) {

    int __evidence_len = bb.getInt();
    evidence = new java.util.ArrayList<ros.pkg.rosmln.msg.AtomProbPair>(__evidence_len);
    for(int __i=0; __i<__evidence_len; __i++) {
      ros.pkg.rosmln.msg.AtomProbPair __tmp = new ros.pkg.rosmln.msg.AtomProbPair();
      __tmp.deserialize(bb);
      evidence.add(__tmp);;
    }
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof MLNDatabase))
      return false;
    MLNDatabase other = (MLNDatabase) o;
    return
      evidence.equals(other.evidence) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.evidence == null ? 0 : this.evidence.hashCode());
    return result;
  }
} // class MLNDatabase

