/* Auto-generated by genmsg_java.py for file /home/ai/Documents/Aptana_Studio_3_Workspace/pracmln/rosmln/msg/MLNQuery.msg */

package ros.pkg.rosmln.msg;

import java.nio.ByteBuffer;

public class MLNQuery extends ros.communication.Message {

  public java.lang.String queries = new java.lang.String();

  public MLNQuery() {
  }

  public static java.lang.String __s_getDataType() { return "rosmln/MLNQuery"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "a3b350632bc5b9feec81a4939be5737a"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "string queries\n" +
"\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public MLNQuery clone() {
    MLNQuery c = new MLNQuery();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4 + queries.length();
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, queries);
  }

  public void deserialize(ByteBuffer bb) {
    queries = Serialization.readString(bb);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof MLNQuery))
      return false;
    MLNQuery other = (MLNQuery) o;
    return
      queries.equals(other.queries) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.queries == null ? 0 : this.queries.hashCode());
    return result;
  }
} // class MLNQuery

