/* Auto-generated by genmsg_java.py for file /home/ai/Documents/Aptana_Studio_3_Workspace/pracmln/rosmln/msg/MRFClique.msg */

package ros.pkg.rosmln.msg;

import java.nio.ByteBuffer;

public class MRFClique extends ros.communication.Message {

  public java.util.ArrayList<java.lang.String> variables = new java.util.ArrayList<java.lang.String>();

  public MRFClique() {
  }

  public static java.lang.String __s_getDataType() { return "rosmln/MRFClique"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "8f184382c36d538fab610317191b119e"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "string[] variables\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public MRFClique clone() {
    MRFClique c = new MRFClique();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4;
    for(java.lang.String val : variables) {
      __l += 4 + val.length();
    }
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.putInt(variables.size());
    for(java.lang.String val : variables) {
      Serialization.writeString(bb, val);
    }
  }

  public void deserialize(ByteBuffer bb) {

    int __variables_len = bb.getInt();
    variables = new java.util.ArrayList<java.lang.String>(__variables_len);
    for(int __i=0; __i<__variables_len; __i++) {
      variables.add(Serialization.readString(bb));
    }
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof MRFClique))
      return false;
    MRFClique other = (MRFClique) o;
    return
      variables.equals(other.variables) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.variables == null ? 0 : this.variables.hashCode());
    return result;
  }
} // class MRFClique

