/* Auto-generated by genmsg_cpp for file /home/ai/Documents/Aptana_Studio_3_Workspace/pracmln/rosmln/srv/MLNInterface.srv */

package ros.pkg.rosmln.srv;

import java.nio.ByteBuffer;


public class MLNInterface extends ros.communication.Service<MLNInterface.Request, MLNInterface.Response> {

  public static java.lang.String __s_getDataType() { return "rosmln/MLNInterface"; }
  public static java.lang.String __s_getMD5Sum() { return "4d059bedd2ff0f23f7c969691f98ba7f"; }

  public java.lang.String getDataType() { return MLNInterface.__s_getDataType(); }
  public java.lang.String getMD5Sum() { return MLNInterface.__s_getMD5Sum(); }

  public MLNInterface.Request createRequest() {
    return new MLNInterface.Request();
  }

  public MLNInterface.Response createResponse() {
    return new MLNInterface.Response();
  }

static public class Request extends ros.communication.Message {

  public ros.pkg.rosmln.msg.MLNQuery query = new ros.pkg.rosmln.msg.MLNQuery();
  public ros.pkg.rosmln.msg.MLNConfig config = new ros.pkg.rosmln.msg.MLNConfig();

  public Request() {
  }

  public static java.lang.String __s_getDataType() { return "rosmln/MLNInterfaceRequest"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "62568d74f21c9322ed52fdd3d72d116d"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "4d059bedd2ff0f23f7c969691f98ba7f"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "MLNQuery query\n" +
"MLNConfig config\n" +
"\n" +
"================================================================================\n" +
"MSG: rosmln/MLNQuery\n" +
"string queries\n" +
"\n" +
"\n" +
"================================================================================\n" +
"MSG: rosmln/MLNConfig\n" +
"string mlnFiles\n" +
"string db\n" +
"string method\n" +
"string engine\n" +
"string output_filename\n" +
"bool saveResults\n" +
"string logic\n" +
"string grammar\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Request clone() {
    Request c = new Request();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += query.serializationLength();
    __l += config.serializationLength();
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    query.serialize(bb, seq);
    config.serialize(bb, seq);
  }

  public void deserialize(ByteBuffer bb) {
    query.deserialize(bb);
    config.deserialize(bb);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Request))
      return false;
    Request other = (Request) o;
    return
      query.equals(other.query) &&
      config.equals(other.config) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.query == null ? 0 : this.query.hashCode());
    result = prime * result + (this.config == null ? 0 : this.config.hashCode());
    return result;
  }
} // class Request

static public class Response extends ros.communication.Message {

  public ros.pkg.rosmln.msg.MLNDatabase response = new ros.pkg.rosmln.msg.MLNDatabase();

  public Response() {
  }

  public static java.lang.String __s_getDataType() { return "rosmln/MLNInterfaceResponse"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "2178741cf410384187aa8e9ebc5ba8ae"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "4d059bedd2ff0f23f7c969691f98ba7f"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "MLNDatabase response\n" +
"\n" +
"\n" +
"================================================================================\n" +
"MSG: rosmln/MLNDatabase\n" +
"AtomProbPair[] evidence\n" +
"\n" +
"================================================================================\n" +
"MSG: rosmln/AtomProbPair\n" +
"string atom\n" +
"float32 prob\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Response clone() {
    Response c = new Response();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += response.serializationLength();
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    response.serialize(bb, seq);
  }

  public void deserialize(ByteBuffer bb) {
    response.deserialize(bb);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Response))
      return false;
    Response other = (Response) o;
    return
      response.equals(other.response) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.response == null ? 0 : this.response.hashCode());
    return result;
  }
} // class Response

} //class

