language: python
python:
  - 2.7

# On a 32-bit Ubuntu Linux 11.10 (server edition):
# $ sudo apt-get install libboost-python-dev
# $ svn co -q http://pyv8.googlecode.com/svn/trunk/ pyv8-read-only
# $ cd pyv8-read-only
# $ svn co -q http://v8.googlecode.com/svn/trunk/ build/v8
# $ DEBUG=false python setup.py build
# $ cd build
# $ mv lib.linux-i686-2.7/ pyv8-build
# $ tar czvf pyv8-build.tar.gz pyv8-build/
# Upload pyv8-build.tar.gz to https://github.com/pyjs/pyjs/downloads

install:
  - sudo apt-get install libboost-python-dev
  - wget https://github.com/downloads/pyjs/pyjs/pyv8-build.2012-05-15.tar.gz
  - tar xzvf pyv8-build.2012-05-15.tar.gz

script:
  - export PYTHONPATH=`pwd`/pyv8-build
  - cd examples/libtest/
  - python ../../pyv8/pyv8run.py LibTest

notifications:
  irc:
    channels:
      - "irc.freenode.org#pyjs"
    use_notice: true
    skip_join: true
